### PR TITLE
fix: wrong link

### LINKED ISSUE #68: Wrong dune dashboard link
## Description

https://gnosis-safe.io/security
`Statistics` button containing wrong link -> https://explore.duneanalytics.com/dashboard/gnosis-safe_2

## Environment
all browsers 

## Steps to reproduce
 1. Go to
https://gnosis-safe.io/security

## Expected result
`Statistics` link to 
https://dune.com/safe/ethereum

## Obtained result
`Statistics` link to 
https://explore.duneanalytics.com/dashboard/gnosis-safe_2

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #68

## How this PR fixes it.

The incorrect link has been exchanged with the correct one (`https://dune.com/safe/ethereum`) on the security page.

### CODE REVIEW

File: src/components/security/Main.tsx [hunk 1]
```diff
@@ -169,7 +169,7 @@ const MainSection = () => {
             </a>
           </UsdWorthDate>
           <SButtonLink
-            url="https://explore.duneanalytics.com/dashboard/gnosis-safe_2"
+            url="https://gnosis-safe.io/security"
```
Comment (katspaugh) [inline src/components/security/Main.tsx:172]: As per the issue, this page should link to https://dune.com/safe/ethereum, not to itself.

**Review by katspaugh — APPROVED** [review]
✅
